version: '3'

services:
  db:
    image: mysql
    container_name: db
    command: ["--init-file=/tmp/mysql-init.sql", "--default-authentication-plugin=mysql_native_password"]
    restart: always
    environment:
      MYSQL_NATIVE_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: '%'
      MYSQL_USER: 'scraper'
    volumes:
      - ./db_dir:/var/lib/mysql
      - ./mysql-init.sql:/tmp/mysql-init.sql
    ports:
      - "3306:3306"
    expose:
      - 3306

volumes:
  db_dir:
